CREATE TABLE IF NOT EXISTS providers (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  env_type VARCHAR(8) NOT NULL DEFAULT 'dev',
  console_ip VARCHAR(45) NOT NULL,
  root_domain VARCHAR(190) NOT NULL,
  arch VARCHAR(32) NOT NULL DEFAULT 'X86（Intel）',
  node_count INT NOT NULL DEFAULT 0,
  username VARCHAR(64) NOT NULL,
  password_enc VARBINARY(1024) NOT NULL,
  project_name VARCHAR(64) NOT NULL,
  user_domain VARCHAR(64) NOT NULL,
  project_domain VARCHAR(64) NOT NULL,
  timeout_sec INT NOT NULL DEFAULT 30,
  sync_interval_min INT NOT NULL DEFAULT 10,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  write_enabled TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'unknown',
  last_verify_at DATETIME(3) NULL,
  last_verify MEDIUMTEXT NULL,
  last_sync_at DATETIME(3) NULL,
  last_sync_try_at DATETIME(3) NULL,
  last_sync_error VARCHAR(512) NOT NULL DEFAULT '',
  vm_count INT NOT NULL DEFAULT 0,
  volume_count INT NOT NULL DEFAULT 0,
  network_count INT NOT NULL DEFAULT 0,
  zones VARCHAR(2048) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  UNIQUE KEY uk_providers_name (name),
  UNIQUE KEY uk_providers_ip (console_ip),
  UNIQUE KEY uk_providers_root (root_domain),
  KEY idx_providers_env (env_type),
  KEY idx_providers_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  kind VARCHAR(16) NOT NULL,
  provider_id VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  message VARCHAR(512) NOT NULL DEFAULT '',
  started_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  KEY idx_tasks_provider (provider_id),
  KEY idx_tasks_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
